import type { Metadata } from 'next';
import './globals.css';
import { UserProvider } from './contexts/user-context';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <UserProvider>{children}</UserProvider>
            </body>
        </html>
    );
}
